/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bicycle_model_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[15] = {10, 2, 0, 5, 10, 2, 3, 4, 8, 9, 2, 3, 4, 8, 9};
static const casadi_int casadi_s4[5] = {0, 2, 0, 0, 0};

/* bicycle_model_constr_h_fun_jac_uxt_zt:(i0[8],i1[2],i2[],i3[])->(o0[2],o1[10x2,10nz],o2[0x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, *w34=w+34, w35, w36, w37, w38;
  /* #0: @0 = 0.5 */
  w0 = 5.0000000000000000e-001;
  /* #1: @1 = 4000 */
  w1 = 4000.;
  /* #2: @2 = input[0][7] */
  w2 = arg[0] ? arg[0][7] : 0;
  /* #3: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #4: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #5: @4 = input[0][6] */
  w4 = arg[0] ? arg[0][6] : 0;
  /* #6: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #7: @6 = (@3*@5) */
  w6  = (w3*w5);
  /* #8: @7 = 0.5 */
  w7 = 5.0000000000000000e-001;
  /* #9: @2 = (@7*@2) */
  w2  = (w7*w2);
  /* #10: @6 = (@6+@2) */
  w6 += w2;
  /* #11: @2 = -4560.4 */
  w2 = -4.5603999999999996e+003;
  /* #12: @8 = 8 */
  w8 = 8.;
  /* #13: @9 = 0.4 */
  w9 = 4.0000000000000002e-001;
  /* #14: @10 = input[0][2] */
  w10 = arg[0] ? arg[0][2] : 0;
  /* #15: @11 = 0.9 */
  w11 = 9.0000000000000002e-001;
  /* #16: @12 = input[0][0] */
  w12 = arg[0] ? arg[0][0] : 0;
  /* #17: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #18: @13 = (@10+@13) */
  w13  = (w10+w13);
  /* #19: @14 = input[0][1] */
  w14 = arg[0] ? arg[0][1] : 0;
  /* #20: @15 = atan2(@13,@14) */
  w15  = atan2(w13,w14);
  /* #21: @15 = (@15-@4) */
  w15 -= w4;
  /* #22: @16 = (@9*@15) */
  w16  = (w9*w15);
  /* #23: @17 = -0.5 */
  w17 = -5.0000000000000000e-001;
  /* #24: @18 = 0.4 */
  w18 = 4.0000000000000002e-001;
  /* #25: @19 = (@18*@15) */
  w19  = (w18*w15);
  /* #26: @20 = 0.4 */
  w20 = 4.0000000000000002e-001;
  /* #27: @15 = (@20*@15) */
  w15  = (w20*w15);
  /* #28: @21 = atan(@15) */
  w21 = atan( w15 );
  /* #29: @19 = (@19-@21) */
  w19 -= w21;
  /* #30: @19 = (@17*@19) */
  w19  = (w17*w19);
  /* #31: @16 = (@16-@19) */
  w16 -= w19;
  /* #32: @19 = atan(@16) */
  w19 = atan( w16 );
  /* #33: @19 = (@8*@19) */
  w19  = (w8*w19);
  /* #34: @21 = sin(@19) */
  w21 = sin( w19 );
  /* #35: @21 = (@2*@21) */
  w21  = (w2*w21);
  /* #36: @22 = sin(@4) */
  w22 = sin( w4 );
  /* #37: @23 = (@21*@22) */
  w23  = (w21*w22);
  /* #38: @6 = (@6-@23) */
  w6 -= w23;
  /* #39: @23 = 500 */
  w23 = 500.;
  /* #40: @6 = (@6/@23) */
  w6 /= w23;
  /* #41: output[0][0] = @6 */
  if (res[0]) res[0][0] = w6;
  /* #42: @6 = cos(@4) */
  w6 = cos( w4 );
  /* #43: @23 = (@21*@6) */
  w23  = (w21*w6);
  /* #44: @24 = -4000 */
  w24 = -4000.;
  /* #45: @25 = 8 */
  w25 = 8.;
  /* #46: @26 = 0.45 */
  w26 = 4.5000000000000001e-001;
  /* #47: @10 = (@10-@12) */
  w10 -= w12;
  /* #48: @12 = atan2(@10,@14) */
  w12  = atan2(w10,w14);
  /* #49: @27 = (@26*@12) */
  w27  = (w26*w12);
  /* #50: @28 = -0.5 */
  w28 = -5.0000000000000000e-001;
  /* #51: @29 = 0.45 */
  w29 = 4.5000000000000001e-001;
  /* #52: @30 = (@29*@12) */
  w30  = (w29*w12);
  /* #53: @31 = 0.45 */
  w31 = 4.5000000000000001e-001;
  /* #54: @12 = (@31*@12) */
  w12  = (w31*w12);
  /* #55: @32 = atan(@12) */
  w32 = atan( w12 );
  /* #56: @30 = (@30-@32) */
  w30 -= w32;
  /* #57: @30 = (@28*@30) */
  w30  = (w28*w30);
  /* #58: @27 = (@27-@30) */
  w27 -= w30;
  /* #59: @30 = atan(@27) */
  w30 = atan( w27 );
  /* #60: @30 = (@25*@30) */
  w30  = (w25*w30);
  /* #61: @32 = sin(@30) */
  w32 = sin( w30 );
  /* #62: @32 = (@24*@32) */
  w32  = (w24*w32);
  /* #63: @23 = (@23+@32) */
  w23 += w32;
  /* #64: @32 = sin(@4) */
  w32 = sin( w4 );
  /* #65: @33 = (@3*@32) */
  w33  = (w3*w32);
  /* #66: @23 = (@23+@33) */
  w23 += w33;
  /* #67: @33 = 500 */
  w33 = 500.;
  /* #68: @23 = (@23/@33) */
  w23 /= w33;
  /* #69: output[0][1] = @23 */
  if (res[0]) res[0][1] = w23;
  /* #70: @34 = zeros(10x2,10nz) */
  casadi_clear(w34, 10);
  /* #71: @23 = sq(@13) */
  w23 = casadi_sq( w13 );
  /* #72: @33 = sq(@14) */
  w33 = casadi_sq( w14 );
  /* #73: @23 = (@23+@33) */
  w23 += w33;
  /* #74: @33 = (@14/@23) */
  w33  = (w14/w23);
  /* #75: @19 = cos(@19) */
  w19 = cos( w19 );
  /* #76: @35 = 0.002 */
  w35 = 2.0000000000000000e-003;
  /* #77: @36 = ones(2x1,1nz) */
  w36 = 1.;
  /* #78: {@37, NULL} = vertsplit(@36) */
  w37 = w36;
  /* #79: @35 = (@35*@37) */
  w35 *= w37;
  /* #80: @22 = (@22*@35) */
  w22 *= w35;
  /* #81: @22 = (@2*@22) */
  w22  = (w2*w22);
  /* #82: @22 = (@19*@22) */
  w22  = (w19*w22);
  /* #83: @22 = (@8*@22) */
  w22  = (w8*w22);
  /* #84: @37 = 1 */
  w37 = 1.;
  /* #85: @16 = sq(@16) */
  w16 = casadi_sq( w16 );
  /* #86: @37 = (@37+@16) */
  w37 += w16;
  /* #87: @22 = (@22/@37) */
  w22 /= w37;
  /* #88: @16 = (@17*@22) */
  w16  = (w17*w22);
  /* #89: @36 = (@18*@16) */
  w36  = (w18*w16);
  /* #90: @38 = 1 */
  w38 = 1.;
  /* #91: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #92: @38 = (@38+@15) */
  w38 += w15;
  /* #93: @16 = (@16/@38) */
  w16 /= w38;
  /* #94: @16 = (@20*@16) */
  w16  = (w20*w16);
  /* #95: @36 = (@36-@16) */
  w36 -= w16;
  /* #96: @22 = (@9*@22) */
  w22  = (w9*w22);
  /* #97: @36 = (@36-@22) */
  w36 -= w22;
  /* #98: @22 = (@33*@36) */
  w22  = (w33*w36);
  /* #99: @16 = (@11*@22) */
  w16  = (w11*w22);
  /* #100: (@34[0] = @16) */
  for (rr=w34+0, ss=(&w16); rr!=w34+1; rr+=1) *rr = *ss++;
  /* #101: @13 = (@13/@23) */
  w13 /= w23;
  /* #102: @23 = (@13*@36) */
  w23  = (w13*w36);
  /* #103: @23 = (-@23) */
  w23 = (- w23 );
  /* #104: (@34[1] = @23) */
  for (rr=w34+1, ss=(&w23); rr!=w34+2; rr+=1) *rr = *ss++;
  /* #105: (@34[2] = @22) */
  for (rr=w34+2, ss=(&w22); rr!=w34+3; rr+=1) *rr = *ss++;
  /* #106: @36 = (-@36) */
  w36 = (- w36 );
  /* #107: @22 = cos(@4) */
  w22 = cos( w4 );
  /* #108: @23 = (@21*@35) */
  w23  = (w21*w35);
  /* #109: @22 = (@22*@23) */
  w22 *= w23;
  /* #110: @36 = (@36-@22) */
  w36 -= w22;
  /* #111: @22 = sin(@4) */
  w22 = sin( w4 );
  /* #112: @23 = (@3*@35) */
  w23  = (w3*w35);
  /* #113: @22 = (@22*@23) */
  w22 *= w23;
  /* #114: @36 = (@36-@22) */
  w36 -= w22;
  /* #115: (@34[3] = @36) */
  for (rr=w34+3, ss=(&w36); rr!=w34+4; rr+=1) *rr = *ss++;
  /* #116: @7 = (@7*@35) */
  w7 *= w35;
  /* #117: @5 = (@5*@35) */
  w5 *= w35;
  /* #118: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #119: @7 = (@7+@5) */
  w7 += w5;
  /* #120: @7 = (@1*@7) */
  w7  = (w1*w7);
  /* #121: (@34[4] = @7) */
  for (rr=w34+4, ss=(&w7); rr!=w34+5; rr+=1) *rr = *ss++;
  /* #122: @7 = 0.002 */
  w7 = 2.0000000000000000e-003;
  /* #123: @5 = ones(2x1,1nz) */
  w5 = 1.;
  /* #124: {NULL, @35} = vertsplit(@5) */
  w35 = w5;
  /* #125: @7 = (@7*@35) */
  w7 *= w35;
  /* #126: @6 = (@6*@7) */
  w6 *= w7;
  /* #127: @2 = (@2*@6) */
  w2 *= w6;
  /* #128: @19 = (@19*@2) */
  w19 *= w2;
  /* #129: @8 = (@8*@19) */
  w8 *= w19;
  /* #130: @8 = (@8/@37) */
  w8 /= w37;
  /* #131: @17 = (@17*@8) */
  w17 *= w8;
  /* #132: @38 = (@17/@38) */
  w38  = (w17/w38);
  /* #133: @20 = (@20*@38) */
  w20 *= w38;
  /* #134: @18 = (@18*@17) */
  w18 *= w17;
  /* #135: @20 = (@20-@18) */
  w20 -= w18;
  /* #136: @9 = (@9*@8) */
  w9 *= w8;
  /* #137: @20 = (@20+@9) */
  w20 += w9;
  /* #138: @33 = (@33*@20) */
  w33 *= w20;
  /* #139: @11 = (@11*@33) */
  w11 *= w33;
  /* #140: @9 = sq(@10) */
  w9 = casadi_sq( w10 );
  /* #141: @8 = sq(@14) */
  w8 = casadi_sq( w14 );
  /* #142: @9 = (@9+@8) */
  w9 += w8;
  /* #143: @14 = (@14/@9) */
  w14 /= w9;
  /* #144: @30 = cos(@30) */
  w30 = cos( w30 );
  /* #145: @24 = (@24*@7) */
  w24 *= w7;
  /* #146: @30 = (@30*@24) */
  w30 *= w24;
  /* #147: @25 = (@25*@30) */
  w25 *= w30;
  /* #148: @30 = 1 */
  w30 = 1.;
  /* #149: @27 = sq(@27) */
  w27 = casadi_sq( w27 );
  /* #150: @30 = (@30+@27) */
  w30 += w27;
  /* #151: @25 = (@25/@30) */
  w25 /= w30;
  /* #152: @28 = (@28*@25) */
  w28 *= w25;
  /* #153: @30 = 1 */
  w30 = 1.;
  /* #154: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #155: @30 = (@30+@12) */
  w30 += w12;
  /* #156: @30 = (@28/@30) */
  w30  = (w28/w30);
  /* #157: @31 = (@31*@30) */
  w31 *= w30;
  /* #158: @29 = (@29*@28) */
  w29 *= w28;
  /* #159: @31 = (@31-@29) */
  w31 -= w29;
  /* #160: @26 = (@26*@25) */
  w26 *= w25;
  /* #161: @31 = (@31+@26) */
  w31 += w26;
  /* #162: @14 = (@14*@31) */
  w14 *= w31;
  /* #163: @11 = (@11-@14) */
  w11 -= w14;
  /* #164: (@34[5] = @11) */
  for (rr=w34+5, ss=(&w11); rr!=w34+6; rr+=1) *rr = *ss++;
  /* #165: @13 = (@13*@20) */
  w13 *= w20;
  /* #166: @13 = (-@13) */
  w13 = (- w13 );
  /* #167: @10 = (@10/@9) */
  w10 /= w9;
  /* #168: @10 = (@10*@31) */
  w10 *= w31;
  /* #169: @13 = (@13-@10) */
  w13 -= w10;
  /* #170: (@34[6] = @13) */
  for (rr=w34+6, ss=(&w13); rr!=w34+7; rr+=1) *rr = *ss++;
  /* #171: @14 = (@14+@33) */
  w14 += w33;
  /* #172: (@34[7] = @14) */
  for (rr=w34+7, ss=(&w14); rr!=w34+8; rr+=1) *rr = *ss++;
  /* #173: @14 = cos(@4) */
  w14 = cos( w4 );
  /* #174: @3 = (@3*@7) */
  w3 *= w7;
  /* #175: @14 = (@14*@3) */
  w14 *= w3;
  /* #176: @4 = sin(@4) */
  w4 = sin( w4 );
  /* #177: @21 = (@21*@7) */
  w21 *= w7;
  /* #178: @4 = (@4*@21) */
  w4 *= w21;
  /* #179: @14 = (@14-@4) */
  w14 -= w4;
  /* #180: @14 = (@14-@20) */
  w14 -= w20;
  /* #181: (@34[8] = @14) */
  for (rr=w34+8, ss=(&w14); rr!=w34+9; rr+=1) *rr = *ss++;
  /* #182: @32 = (@32*@7) */
  w32 *= w7;
  /* #183: @0 = (@0*@32) */
  w0 *= w32;
  /* #184: @1 = (@1*@0) */
  w1 *= w0;
  /* #185: (@34[9] = @1) */
  for (rr=w34+9, ss=(&w1); rr!=w34+10; rr+=1) *rr = *ss++;
  /* #186: output[1][0] = @34 */
  casadi_copy(w34, 10, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bicycle_model_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_model_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bicycle_model_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_model_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bicycle_model_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void bicycle_model_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bicycle_model_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bicycle_model_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real bicycle_model_constr_h_fun_jac_uxt_zt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_model_constr_h_fun_jac_uxt_zt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_model_constr_h_fun_jac_uxt_zt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_model_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_model_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bicycle_model_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 48;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
